language: python
python:
  - "2.7"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python -m unittest discover
  - behave
  - coverage erase
  - coverage run test_webapp.py && coverage html
  - pylint --output-format=text webapp.py

after_success:
  - codecov
  
deploy:
  provider: heroku  
  app : gold5
  api_key: 
    secure: "f1af6cbb-4616-4964-b455-a4f1af3fb1ae"
