language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python main.py
deploy:
  provider: heroku  
  api_key: 
    secure: "f1af6cbb-4616-4964-b455-a4f1af3fb1ae"
